var PakistanDrugsList = [
    "Paracetamol",
    "Ibuprofen",
    "Aspirin",
    "Diclofenac",
    "Naproxen",
    "Amoxicillin",
    "Amoxicillin/Clavulanic acid",
    "Azithromycin",
    "Ceftriaxone",
    "Cefuroxime",
    "Cefixime",
    "Ciprofloxacin",
    "Levofloxacin",
    "Metronidazole",
    "Doxycycline",
    "Clarithromycin",
    "Gentamicin",
    "Vancomycin",
    "Co-trimoxazole",
    "Nitrofurantoin",
    "Flucloxacillin",
    "Erythromycin",
    "Omeprazole",
    "Pantoprazole",
    "Ranitidine",
    "Lansoprazole",
    "Esomeprazole",
    "Salbutamol",
    "Ipratropium",
    "Budesonide",
    "Fluticasone",
    "Montelukast",
    "Insulin (Human)",
    "Insulin (Analogs)",
    "Metformin",
    "Glibenclamide",
    "Glimepiride",
    "Sitagliptin",
    "Pioglitazone",
    "Amlodipine",
    "Enalapril",
    "Lisinopril",
    "Losartan",
    "Hydrochlorothiazide",
    "Spironolactone",
    "Nifedipine",
    "Carvedilol",
    "Propranolol",
    "Atorvastatin",
    "Simvastatin",
    "Rosuvastatin",
    "Warfarin",
    "Rivaroxaban",
    "Heparin",
    "Enoxaparin",
    "Paracetamol + Codeine",
    "Tramadol",
    "Morphine",
    "Amphogel",
    "Loperamide",
    "Ondansetron",
    "Metoclopramide",
    "Prednisolone",
    "Dexamethasone",
    "Hydrocortisone",
    "Methylprednisolone",
    "Vitamin B Complex",
    "Vitamin B12 (Methylcobalamin)",
    "Vitamin D3 (Cholecalciferol)",
    "Calcium carbonate",
    "Folic acid",
    "Cetirizine",
    "Loratadine",
    "Chlorpheniramine",
    "Insulin Glargine",
    "Insulin Lispro",
    "Azathioprine",
    "Methotrexate",
    "Cyclophosphamide",
    "Tacrolimus",
    "Normal saline",
    "Dextrose 5%",
    "Dextrose 10%",
    "Mupirocin",
    "Benzylpenicillin",
    "Clindamycin",
    "Linezolid",
    "Nevirapine",
    "Tenofovir",
    "Lamivudine",
    "Efavirenz",
    "Ivermectin",
    "Albendazole",
    "Mebendazole",
    "Oxytocin",
    "Misoprostol",
    "Fluconazole",
    "Nystatin",
    "Itraconazole",
    "Polymyxin B",
    "Polymal",
    "Neomycin",
    "Aminophylline",
    "Cholecalciferol",
    "Ergocalciferol",
    "Pyridoxine",
    "Thiamine",
    "Croxim",
    "Crocin",
    "Panadol",
    "Myelin",
    "Myelin G",
    "Augmentin",
    "Zithromax",
    "Cefspan",
    "Flagyl",
    "Voltaren",
    "Brufen",
    "Tobramycin eye drops",
    "Moxifloxacin eye drops",
    "Prednisolone eye drops",
    "Silver sulfadiazine",
    "ORS",
    "Paracetamol syrup",
    "Amoxicillin suspension",
    "Chloroquine",
    "Artemether + Lumefantrine",
    "Primaquine",
    "Fluoxetine",
    "Sertraline",
    "Diazepam",
    "Lorazepam",
    "Clonazepam",
    "Carbamazepine",
    "Valproate",
    "Gabapentin",
    "Pregabalin",
    "Hydrocortisone cream",
    "Clotrimazole cream",
    "Ketoconazole cream",
    "Furosemide",
    "Magnesium sulfate",
    "Calcium gluconate",
    "Levonorgestrel"
];
