var NHSDrugsList = [
    "Abacavir sulphate", "Abacavir sulphate/Lamivudine", "Abacavir sulphate/Lamivudine/Zidovudine", "Abatacept", "Abciximab", "Abelcet", "Abilify", "Acamprosate calcium", "Acarbose", "Accolate",
    "Accrete D3", "Accupro", "Accuretic", "Acea", "Acebutolol", "Aceclofenac", "Acemetacin", "Acenocoumarol", "Acepril", "Acetazolamide", "Acetic acid glacial/Dexamethasone/Neomycin sulphate",
    "Acetylcholine chloride", "Acetylcysteine", "Acezide", "Aciclovir", "Aciclovir sodium", "Acidex liquid", "Acipimox", "Acitretin", "Aclasta", "Acnamino", "Acnecide gel", "Acnecide wash", "Acnisal",
    "Acnocin", "Acriflex cream", "Acrivastine", "Actifed Multi-Action Chesty Coughs liquid", "Actifed Multi-Action Dry Coughs liquid", "Actilyse", "Activated charcoal/Magnesium hydroxide", "Actonel",
    "Actonel Combi", "Actonorm Gel", "Actos", "Actrapid", "Acular", "ACWY Vax", "Adalat", "Adalimumab", "Adapalene", "Adartrel", "Adcal", "Adcal D3", "Adcirca", "Adcortyl", "Adefovir dipivoxil", "Adenocor",
    "Adenosine", "Adenuric", "Adios", "Adios Max", "Adipine", "Adizem", "Adrenaline", "Adrenaline acid tartrate", "Advagraf", "AeroBec", "Afinitor", "Aggrastat", "Agomelatine", "Agrippal", "Aknemycin Plus",
    "Aldactide", "Aldactone", "Aldara", "Aldesleukin", "Alendronate sodium", "Alendronate sodium/Colecalciferol", "Alfacalcidol", "Alfentanil hydrochloride", "Alfuzosin hydrochloride",
    "Alginate/Magnesium trisilicate/Sodium bicarbonate/Aluminium hydroxide", "Alimemazine tartrate", "Alimta", "Aliskiren", "Alitretinoin", "Alkeran injection", "Alkeran tablets", "Allantoin/Lidocaine",
    "Allegron", "Allopurinol", "Almogran", "Almotriptan hydrogen malate", "Alomide", "Alphaderm", "Alphagan", "AlphaNine", "Alphosyl 2 in 1 shampoo", "Alprazolam", "Alprostadil", "Altacite Plus", "Altargo",
    "Alteplase", "Alu-Cap capsules", "Aluminium hydroxide", "Aluminium hydroxide/Calcium carbonate/Magnesium carbonate", "Aluminium hydroxide/Magnesium hydroxide/Simeticone", "Alverine", "Amantadine hydrochloride",
    "Amaryl", "Ambirix", "AmBisome", "Ambrisentan", "Amias", "Amikacin sulphate", "Amikin", "Amilamont", "Amiloride", "Amiloride/Furosemide", "Amiloride/Hydrochlorothiazide", "Aminophylline", "Amiodarone",
    "Amisulpride", "Amitriptyline", "Amlodipine", "Amlodipine besilate/Valsartan", "Amlostin", "Ammonia", "Ammonia and Ipecacuanha mixture", "Ammonia/Eucalyptus", "Amorolfine hydrochloride", "Amoxicillin sodium",
    "Amoxicillin sodium/Potassium clavulanate", "Amoxicillin trihydrate", "Amoxicillin trihydrate/Potassium clavulanate", "Amoxil", "Amoxil injection", "Amphocil", "Amphotericin", "Amphotericin phospholipid complex",
    "Ampicillin", "Amylase/Lipase/Protease", "Anabact", "Anacal Rectal ointment", "Anadin Extra Soluble tablets", "Anadin Extra tablets", "Anadin Ibuprofen", "Anadin Original", "Anadin Paracetamol", "Anafranil",
    "Anastrozole", "Anbesol adult gel", "Anbesol liquid", "Anbesol teething gel", "Ancotil", "Anectine", "Anexate", "Angeliq", "Angettes", "Angiox", "Angitil", "Anhydrol forte", "Anidulafungin",
    "Anise oil/Menthol/Capsicum tincture", "Antabuse", "Antazoline/Xylometazoline", "Antepsin", "Anthisan", "Anthisan Bite and Sting cream", "Anti-D (RHO) Immunoglobulin", "Antithymocyte immunoglobulin (rabbit)",
    "Anugesic-HC cream", "Anugesic-HC suppository", "Anusol cream", "Anusol ointment", "Anusol Plus HC", "Anusol suppositories", "Apidra", "APO-go", "Apomorphine hydrochloride", "Apraclonidine hydrochloride",
    "Aprepitant", "Apresoline", "Aprinox", "Aprovel", "Aptivus", "Aquadrate", "Aqueous calamine cream", "Aqueous cream", "Aranesp", "Arava", "Arcoxia", "Aredia", "Argipressin", "Aricept", "Arimidex",
    "Aripiprazole", "Arixtra", "Aromasin", "Arpicolin", "Arsenic trioxide", "Artelac", "Artemether/Lumefantrine", "Arthrotec", "Arythmol", "Arzerra", "Asacol", "Asasantin",
    "Ascorbic acid/Amylmetacresol/Dichlorobenzyl alcohol", "Ascorbic acid/Phenylephrine/Paracetamol", "Ashton and Parsons Powders", "Asmabec", "Asmanex", "Asmasal", "Aspirin", "Aspirin/Codeine phosphate",
    "Aspirin/Dipyridamole", "Aspro Clear", "Atarax", "Atazanavir sulphate", "Atenolol", "Atenolol/Chlortalidone", "Atenolol/Nifedipine", "Ativan", "Atorvastatin", "Atovaquone/Proguanil hydrochloride",
    "Atracurium besilate", "Atriance", "Atripla", "Atropine", "Atrovent", "Augmentin", "Augmentin Intravenous", "Augmentin-Duo", "Avamys", "Avastin", "Avaxim", "Avelox", "Avloclor", "Avodart", "Avonex",
    "Axid", "Axsain", "Azactam", "Azathioprine", "Azelaic Acid", "Azelastine hydrochloride", "Azilect", "Azithromycin", "Azithromycin dihydrate", "Azopt", "Aztreonam",

    "Baclofen", "Bactroban", "Balneum Plus bath oil", "Balneum Plus cream", "Balsalazide disodium", "Bambec", "Bambuterol", "Baraclude", "Baratol", "Basiliximab", "Bazetham", "Bazuka", "BCG (Connaught strain)",
    "BCG (TICE strain)", "Beclazone", "Beclometasone dipropionate", "Beclometasone dipropionate/Formoterol fumarate dihydrate", "BecoAllergy", "Beconase", "Bedranol", "Beechams Active Cold Relief caplets",
    "Beechams All-In-One", "Beechams Breathe Clear Hot Honey & Lemon Menthol Flavour", "Beechams Cold and Flu", "Beechams Cold Relief Effervescent tablets", "Beechams Decongestant Plus With Paracetamol",
    "Beechams Flu Plus", "Beechams Flu Plus caplets", "Beechams Max Strength Sore Throat Relief lozenges", "Beechams Powders capsules", "Beechams Ultra All-In-One capsules", "Beechams Ultra All-In-One powder",
    "Belimumab", "Bemiparin", "Benadryl Allergy Relief capsules", "Benadryl Allergy syrup", "Benadryl One A Day tablets", "Benadryl Plus capsules", "Bendroflumethiazide", "Bendroflumethiazide/Timolol",
    "BeneFIX", "Benlysta", "Benylin Chesty Coughs (non-drowsy)", "Benylin Chesty Coughs (Original)", "Benylin Children’s Dry Cough", "Benylin Childrens apple flavour cough syrup",
    "Benylin Childrens Blackcurrant flavour cough syrup", "Benylin Childrens Chesty Cough", "Benylin Children's Chesty Coughs", "Benylin Childrens Night Coughs", "Benylin Cold and Flu Max Strength",
    "Benylin Day and Night tablets", "Benylin Dry Coughs (Non-drowsy)", "Benylin Dry Coughs (Original)", "Benylin Dry Coughs Blackcurrant", "Benylin Four Flu", "Benylin Mucus Cough",
    "Benylin Mucus Cough and Cold All in One tablets", "Benylin Night-Time Mucus Cough", "Benylin Tickly Coughs Non-Drowsy", "Benzalkonium chloride", "Benzalkonium chloride/Dimeticone 350/Hydrocortisone/Nystatin",
    "Benzocaine cream", "Benzocaine oral spray", "Benzocaine/Dequalinium chloride", "Benzocaine/Mepyramine", "Benzocaine/Tyrothricin", "Benzoyl peroxide 4% cream", "Benzoyl peroxide 5% cream",
    "Benzoyl peroxide gel", "Benzoyl peroxide wash", "Benzoyl peroxide/Clindamycin phosphate", "benzoyl peroxide/potassium hydroxyquinoline sulphate", "Benzydamine cream", "Benzydamine mouthwash",
    "Benzydamine oral spray", "Benzyl benzoate/Bismuth oxide/Bismuth subgallate/Hydrocortisone acetate/Peru Balsam/Pramocaine hydrochloride/Zinc oxide",
    "Benzyl benzoate/Bismuth oxide/Bismuth subgallate/Hydrocortisone acetate/Peru Balsam/Zinc oxide", "Benzyl benzoate/Bismuth oxide/Hydrocortisone acetate/Peru Balsam/Pramocaine hydrochloride/Zinc oxide",
    "Benzylpenicillin sodium", "Beta-Adalat", "Betacap", "Beta-Cardone", "Betadine dry powder spray", "Betaferon", "Betagan", "Betahistine dihydrochloride", "Betaloc", "Betamethasone dipropionate",
    "Betamethasone dipropionate/Calcipotriol hydrate", "Betamethasone dipropionate/Calcipotriol monohydrate", "Betamethasone dipropionate/Salicylic acid", "Betamethasone Valerate", "Betamethasone Valerate/Clioquinol",
    "Betamethasone Valerate/Fusidic Acid", "Betamethasone valerate/Neomycin sulphate", "Beta-Prograne", "Betaxolol hydrochloride", "Bethanechol chloride", "Betim", "Betnovate", "Betnovate-C", "Betnovate-N",
    "Betoptic", "Bettamousse", "Bevacizumab", "Bexarotene", "Bezafibrate", "Bezalip", "Bicalutamide", "Bi-Carzem", "BiCNU", "Bimatoprost", "Bimatoprost/Timolol maleate", "Binovum", "Biorphen",
    "Bisacodyl suppositories", "Bisacodyl tablets", "Bismuth subsalicylate", "Bisodol Extra Strong Mint tablets", "Bisodol Indigestion Relief tablets", "Bisoprolol fumarate", "Bivalirudin", "Bleo-Kyowa",
    "Bleomycin sulphate", "Blistex Relief cream", "Bondronat", "Bonefos", "Bonjela", "Bonjela Junior gel", "Bonjela Teething gel", "Bonviva", "Boots Bronchial Cough Mixture", "Boots Rehydration Treatment sachets",
    "Boots Sore Throat And Cough 2 Years Plus linctus", "Bortezomib", "Bosentan", "Botox", "Botulinum Toxin Type A", "Botulinum Toxin Type B", "Bradosol Sugar Free lozenges", "Brentuximab vedotin", "Brevinor",
    "Brevoxyl cream", "Bricanyl", "Bridion", "Brilique", "Brimonidine tartrate", "Brimonidine tartrate/Timolol maleate", "Brinzolamide", "Brochlor", "Brolene Antibiotic Eye Ointment", "Brolene eye drops",
    "Bromocriptine mesilate", "Brufen", "Buccastem", "Budesonide", "Budesonide/Formoterol fumarate dihydrate", "Bumetanide", "Bupivacaine hydrochloride", "Bupivacaine hydrochloride/Adrenaline acid tartrate",
    "Bupivacaine hydrochloride/Glucose monohydrate", "Burinex", "Buscopan", "Buserelin acetate", "Busilvex", "Buspirone", "Busulfan", "Buttercup Bronchostop Cough Pastilles",
    "Buttercup Max Strength Sore Throat lozenge", "Buttercup syrup", "Bydureon", "Byetta",

    "Cabaser", "Cabazitaxel", "Cabergoline", "Cabren", "Cacit", "Cacit D3", "Caelyx", "Caffeine hydrate/Cyclizine hydrochloride/Ergotamine tartrate", "Caffeine/Aspirin/Paracetamol", "Caffeine/Theophylline/Ephedrine",
    "Calamine Lotion", "Calceos", "Calchan", "Calcicard", "Calcichew", "Calcichew D3", "Calcijex", "Calcipotriol", "Calcipotriol hydrate", "Calcitonin (salmon)", "Calcitriol", "Calcium Acetate",
    "Calcium carbonate antacids", "Calcium carbonate supplements", "Calcium Carbonate/Disodium Etidronate", "Calcium carbonate/Sodium bicarbonate/Magnesium carbonate", "Calcium Folinate",
    "Calcium glubionate /Calcium lactobionate", "Calcium Lactate", "Calcium Levofolinate", "Calcium Phosphate/Colecalciferol", "Calcium-Sandoz syrup", "Calcort", "Calcough childrens soothing syrup",
    "Calcough Infant syrup", "Calcough Six Plus", "Calfovit D3", "Calgel Teething gel", "Calmurid HC", "Calpol Six Plus", "Calprofen", "Camcolit", "Campto", "Cancidas", "Candesartan", "Canesten",
    "Canesten Bifonazole Cream", "Canesten HC", "Canesten Oasis", "Canesten Oral And Cream Duo", "Canusal", "Capasal shampoo", "Capecitabine", "Capoten", "Capozide", "Capreomycin sulphate", "Caprin", "Capsaicin",
    "Captopril", "Captopril/Hydrochlorothiazide", "Carace Plus", "Caramet", "Carbamazepine", "Carbetocin", "Carbidopa/Entacapone/Levodopa", "Carbimazole", "Carbocisteine", "Carbo-Dome cream", "Carbomer",
    "Carbomer eye drops", "Carboplatin", "Carboprost trometamol", "Cardene", "Cardicor", "Cardioplen", "Cardioxane", "Cardura", "Carmellose sodium", "Carmustine", "Casodex", "Caspofungin acetate", "Catapres",
    "Caverject", "Cayston", "Ceanel Shampoo", "Cefaclor monohydrate", "Cefadroxil monohydrate", "Cefalexin", "Cefixime", "Cefotaxime sodium", "Ceftazidime pentahydrate", "Ceftriaxone sodium", "Cefuroxime axetil",
    "Cefuroxime sodium", "Celebrex", "Celecoxib", "Celectol", "Celevac Tablets", "Celiprolol", "CellCept", "CellCept powder", "Celluvisc", "Celsentri", "Ceplene", "Ceporex", "Cerazette", "Certolizumab pegol",
    "Cerumol Ear Drops", "Cervarix", "Cetirizine liquid", "Cetirizine tablets", "Cetomacrogol Cream Formula A", "Cetraben bath additive", "Cetrimide", "Cetrimide 0.5% cream", "Cetrimide/Benzalkonium chloride",
    "Cetrorelix acetate", "Cetrotide", "Cetuximab", "Cetylpyridinium chloride/Menthol", "Chemydur", "Chirocaine", "Chlorambucil", "Chloramphenicol", "Chloramphenicol sodium succinate", "Chlordiazepoxide",
    "Chlorhexidine gluconate", "Chlorhexidine gluconate/Cetrimide", "Chlorhexidine gluconate/Chlorobutanol", "Chlorhexidine hydrochloride/Neomycin sulphate", "Chlorhexidine/Tetracaine", "Chlorobutanol/Arachis oil",
    "Chlorobutanol/Lidocaine/Alcloxa/Cetrimide", "Chlorocresol/Urea/Cetrimide/Dimeticone", "Chloromycetin", "Chloroquine", "Chloroxylenol", "Chloroxylenol/Triclosan/Edetic acid", "Chlorphenamine maleate",
    "Chlorpromazine hydrochloride", "Chlortalidone", "Cholestagel", "Choline salicylate", "Choragon", "Choriogonadotropin Alfa", "Chorionic gonadotrophin human", "Cialis", "Cibral", "Cicafem", "Ciclesonide",
    "Ciclosporin", "Cilastatin sodium/Imipenem monohydrate", "Cilest", "Cilostazol", "Cimetidine", "Cimzia", "Cinacalcet hydrochloride", "Cinchocaine", "Cinchocaine hydrochloride/Hydrocortisone",
    "Cinchocaine hydrochloride/Prednisolone hexanoate", "Cinnarizine", "Cipralex", "Cipramil", "Cipramil drops", "Ciprofibrate", "Ciprofloxacin", "Ciprofloxacin hydrochloride", "Ciprofloxacin lactate",
    "Ciproxin injection", "Ciproxin suspension", "Ciproxin tablets", "Circadin", "Cisatracurium besilate", "Cisplatin", "Citalopram hydrobromide", "Citalopram hydrochloride", "Citanest", "Citric acid/Ipecacuanha",
    "Citric acid/Sodium bicarbonate/Sodium carbonate", "Cladribine", "Claforan", "Clairette", "Clarelux", "Clarie XL", "Clarithromycin", "Clemastine", "Clenil Modulite", "Clexane", "Climagest", "Climanor",
    "Climaval", "Climesse", "Clindamycin hydrochloride", "Clindamycin phosphate", "Clioquinol/Flumetasone pivalate", "Clobazam", "Clobetasol propionate", "Clobetasone butyrate",
    "Clobetasone butyrate/Nystatin/Oxytetracycline calcium", "Clofarabine", "Clomethiazole", "Clomid", "Clomifene citrate", "Clomipramine", "Clonidine", "Clopamide/Pindolol", "Clopidogrel", "Clopixol Acuphase",
    "Clopixol Conc", "Clopixol tablets", "Clotam", "Clotrimazole", "Clotrimazole/Hydrocortisone", "Clove oil", "Clozapine", "Clozaril", "Coal tar bath additive", "Coal tar cream", "Coal tar lotion",
    "Coal tar shampoo", "Coal tar/Lecithin", "CoAprovel", "Cobalin-H", "Co-beneldopa", "Co-careldopa", "Coconut oil/Salicylic acid/Coal tar distilled", "Co-danthramer", "Codeine/Paracetamol", "Co-Diovan",
    "Codis 500", "Co-fluampicil capsules", "Co-fluampicil injection", "Co-fluampicil oral suspension", "Colazide", "Colchicine", "Colecalciferol/Calcium carbonate", "Colesevelam hydrochloride", "Colestid",
    "Colestipol", "Colestyramine anhydrous", "Colifoam", "Colistimethate sodium", "Colistin sulphate", "Colofac", "Colomycin", "Colomycin injection", "Colomycin syrup", "Colomycin tablet",
    "Colpermin IBS Relief capsules", "Co-magaldrox", "Combigan", "Combivent", "Combivir", "Combodart", "Competact", "Comtess", "Concerta XL", "Condyline", "Conjugated Oestrogens",
    "Conjugated oestrogens/Medroxyprogesterone acetate", "Conjugated Oestrogens/Norgestrel", "Conotrane cream", "Contac Non-Drowsy Dual Relief Tablets", "Copaxone", "Copegus", "Coracten", "Cordarone X", "Cordilox",
    "Corgard", "Corifollitropin alfa", "Corsody Dental gel", "Corsodyl mouthwash", "Corsodyl spray", "Co-simalcite", "CosmoFer", "Cosopt", "Co-trimoxazole", "Cough Nurse Night Time liquid", "Coversyl Arginine",
    "Covonia Catarrh Relief Formula", "Covonia Cold & Flu", "Covonia Dry & Tickly Cough Linctus", "Covonia Dry Cough Sugar Free", "Covonia Herbal Mucus Cough Syrup", "Cozaar", "Cozaar-Comp", "Co-zidocapt", "Creon",
    "Crestor", "Crinone", "Cromogen", "Crotamiton", "Crotamiton/Hydrocortisone", "Cubicin", "Cuprofen", "Cutivate", "Cyanocobalamin", "Cyclizine lactate", "Cyclopentolate hydrochloride",
    "Cyclophosphamide monohydrate", "Cyclo-Progynova 2mg", "Cycloserine", "Cyklokapron", "Cymalon", "Cymbalta", "Cymevene", "Cymex cream", "Cyproheptadine", "Cyprostat", "Cyproterone acetate",
    "Cyproterone acetate/Ethinylestradiol", "Cystrin", "Cytamen", "Cytarabine", "Cytotec",

    "Dabigatran etexilate mesilate", "Dacarbazine citrate", "Daktacort", "Daktarin Oral Gel", "Dalacin", "Dalacin C", "Dalmane", "Dalteparin", "Danaparoid", "Danazol", "Dandrazol", "Danol", "Dantrium",
    "Dantrolene sodium", "Daptomycin", "Daraprim", "Darbepoetin Alfa", "Darifenacin hydrobromide", "Darunavir ethanolate", "Dasatinib", "Daunorubicin hydrochloride citrate", "DaunoXome", "Daxas",
    "Day & Night Nurse capsules", "Day Nurse", "Day Nurse capsules", "DDAVP", "Deca-Durabolin", "Decapeptyl", "Defanac", "Deferasirox", "Deferiprone", "Deflazacort", "Deltacortril", "Deltastab",
    "Demeclocycline hydrochloride", "Denosumab", "Dentinox Colic drops", "Dentinox Cradle Cap shampoo", "Dentinox Teething gel", "Denzapine", "Depakote", "Depixol", "Depixol tablets", "DepoCyte",
    "Depo-Medrone", "Depo-medrone with Lidocaine", "Depo-Provera", "Dequacaine", "Dequadin", "Dequalinium", "Derbac M", "Dermalo bath emollient", "Dermax", "Dermidex", "Dermovate", "Deseril", "Desferal",
    "Desferrioxamine mesilate", "Desloratadine", "DesmoMelt", "Desmopressin acetate", "Desmospray", "Desmotabs", "Desogestrel", "Destolit", "Detrunorm", "Detrusitol", "Dettol Antiseptic cream",
    "Dettol Antiseptic wash", "Dettol liquid", "Dexamethasone", "Dexamethasone sodium metasulphobenzoate/Framycetin sulphate/Gramicidin", "Dexamethasone sodium phosphate",
    "Dexamethasone/Hypromellose/Neomycin sulphate/Polymyxin B sulphate", "Dexamethasone/Tobramycin", "Dexibuprofen", "Dexketoprofen trometamol", "Dexomon", "Dexrazoxane", "Dexsol", "Dextromethorphan",
    "D-GAM", "DHC Continus", "Diamicron", "Diamorphine", "Diamox", "Dianette", "Diazemuls", "Diazepam", "Dichlorobenzyl alcohol/Amylmetacresol", "Diclofenac diethylammonium", "Diclofenac epolamine",
    "Diclofenac potassium", "Diclofenac sodium", "Dicloflex", "Diclomax", "Dicycloverine hydrochloride", "Dicycloverine/Simeticone/Aluminium hydroxide/Magnesium oxide", "Didanosine", "Didronel", "Didronel PMO",
    "Diethylamine salicylate", "Differin", "Difflam cream", "Difflam solution", "Difflam spray", "Diflucan", "Digoxin", "Dihydrocodeine Tartrate", "Dihydrocodeine Tartrate/Paracetamol", "Dilcardia",
    "Dill oil/Sodium bicarbonate/Ginger", "Diloxanide furoate", "Diltiazem", "Dilzem", "Dimeticone", "Dimeticone/Benzalkonium chloride", "Dinoprostone", "Dioctyl", "Dioderm", "Dioralyte", "Dioralyte Relief",
    "Diovan", "Dipentum", "Diphenhydramine", "Diphenhydramine/Ammonium chloride/Menthol", "Diphenhydramine/Caffeine/Ephedrine/Paracetamol", "Diphenhydramine/Dextromethorphan/Menthol",
    "Diphenhydramine/Guaifenesin/Levomenthol", "Diphenhydramine/Levomenthol", "Diphenhydramine/Pholcodine",
    "Diphtheria toxoid/Human poliovirus type 1 inactivated/Human poliovirus type 2 inactivated/Human poliovirus type 3 inactivated/Pertussis antigens/Tetanus toxoid",
    "Diphtheria toxoid/Human poliovirus type 1 inactivated/Human poliovirus type 2 inactivated/Human poliovirus type 3 inactivated/Tetanus toxoid",
    "Diphtheria toxoid/Tetanus toxoid/Pertussis antigens/Human poliovirus type 1 inactivated/Human poliovirus type 2 inactivated/Human poliovirus type 3 inactivated/Haemophilus influenzae type b polysaccharide protein conjugate",
    "Diprivan", "Diprosalic", "Diprosone", "Dipyridamole", "Disipal", "Disodium Etidronate", "Disodium Folinate", "Disodium Pamidronate", "Disopyramide", "Disopyramide phosphate", "Disprin", "Distaclor",
    "Distamine", "Distilled Witch Hazel", "Disulfiram", "Dithranol", "Dithrocream", "Ditropan", "Diurexan", "Dixarit", "Dobutamine hydrochloride", "Docetaxel", "Docusate", "Docusate gel enema",
    "Docusate sodium ear drops", "Do-Do Chesteze", "Dolmatil", "Domperidone", "Domperidone maleate", "Dopamine", "Dopexamine", "Doralese Tiltab", "Dornase alfa", "Dorzolamide hydrochloride",
    "Dorzolamide hydrochloride/Timolol maleate", "Doublebase bath additive", "Doublebase gel", "Doublebase shower gel", "Doublebase wash gel", "Dovobet", "Dovonex", "Dovonex cream", "Doxadura", "Doxazosin",
    "Doxorubicin hydrochloride", "Doxorubin", "Doxycycline hyclate", "Doxycycline monohydrate", "Doxylar", "Dozic", "Drapolene cream", "Dromadol", "Dronedarone hydrochloride", "Drospirenone/Estradiol hemihydrate",
    "Drospirenone/Ethinylestradiol", "Droxia", "Duac", "Dukoral", "Dulcobalance", "Dulcoease", "Dulcolax suppositories", "Dulcolax tablets", "Duloxetine", "Duodopa", "Duofilm", "DuoTrav", "Dutasteride",
    "Dydrogesterone/Estradiol", "Dysport",

    "E45 Itch Relief cream", "Easyhaler Beclometasone", "Easyhaler Budesonide", "Easyhaler Formoterol", "Easyhaler Salbutamol", "Ebixa", "Ecalta", "Eccoxolac", "Econac", "Econazole nitrate", "Ecopace", "Eczmol",
    "Edronax", "Edrophonium chloride", "Efavirenz", "Efcortesol", "Efexor", "Efient", "Eflornithine monohydrate chloride", "Efudix", "Eldepryl", "Electrolade", "Eletriptan hydrobromide", "Elidel", "Ellaone",
    "Elleste Solo", "Ellimans Universal Muscle Rub lotion", "Elocon", "Elonva", "Eloxatin", "Eludril mouthwash", "Eludril spray", "Elvanse", "Emadine", "Emcor", "Emedastine difumarate", "Emend", "Emeside",
    "Emflex", "Emla", "Emselex", "Emtricitabine", "Emtricitabine/Tenofovir disoproxil fumarate", "Emtriva", "Enalapril", "Enalapril/Hydrochlorothiazide", "Enbrel", "Endoxana", "Enfuvirtide", "Engerix B", "Eno",
    "Enoxaparin", "Entacapone", "Entecavir monohydrate", "Entocort", "Enzira", "Epanutin capsules", "Epanutin Infatabs", "Epanutin ready mixed parenteral", "Epanutin suspension", "Epaxal", "Ephedrine hydrochloride",
    "Ephedrine hydrochloride/Chlorphenamine", "Ephedrine nasal drops", "Epilim", "Epinastine hydrochloride", "EpiPen", "Epirubicin hydrochloride", "Epival", "Epivir", "Eplerenone", "Epoetin Alfa", "Epoetin Beta",
    "Epoprostenol", "Eprex", "Eprosartan", "Epsom salts", "Eptacog Alfa", "Eptifibatide", "Erbitux", "Erdosteine", "Erdotin", "Ergometrine maleate", "Ergometrine maleate/Oxytocin", "Erlotinib hydrochloride",
    "Ertapenem sodium", "Eryacne 4", "Erymax", "Erythrocin", "Erythromycin", "Erythromycin ethyl succinate", "Erythromycin lactobionate", "Erythromycin stearate", "Erythromycin/Isotretinoin", "Erythromycin/Tretinoin",
    "Erythromycin/Zinc Acetate", "Erythroped", "Escitalopram", "Esmeron", "Esmya", "Esomeprazole injection", "Esomeprazole tablets", "Estracyt", "Estraderm", "Estradiol", "Estradiol hemihydrate", "Estradiol valerate",
    "Estradiol valerate/Medroxyprogesterone", "Estradiol valerate/Medroxyprogesterone acetate", "Estradiol valerate/Norethisterone", "Estradiol valerate/Norgestrel", "Estradiol/Estriol/Estrone",
    "Estradiol/Norethisterone acetate", "Estradot", "Estramustine sodium phosphate", "Estring", "Estriol", "Etamsylate", "Etanercept", "Ethanolamine", "Ethinylestradiol", "Ethinylestradiol/Etonogestrel",
    "Ethinylestradiol/Gestodene", "Ethinylestradiol/Levonorgestrel", "Ethinylestradiol/Norelgestromin", "Ethinylestradiol/Norethisterone", "Ethinylestradiol/Norethisterone acetate", "Ethinylestradiol/Norgestimate",
    "Ethosuximide", "Etodolac", "Etomidate", "Etonogestrel", "Etopophos", "Etoposide", "Etoposide phosphate", "Etoricoxib", "Etravirine", "Etynodiol diacetate", "Eucalyptus Oil",
    "Eucalyptus/Terpineol/Methyl salicylate/Menthol/Camphor", "Eucalyptus/Thyme/Menthol", "Eucalyptus/Turpentine/Levomenthol/Camphor", "Eucalyptus/Turpentine/Methyl salicylate/Menthol", "Eucreas", "Eumovate",
    "Eurax", "Eurax Hydrocortisone", "Everolimus", "Evista", "Evoltra", "Evorel", "Evorel Conti", "Evorel Sequi", "Evra", "Exelon", "Exelon patches", "Exemestane", "Exenatide", "Exforge", "Exjade", "Ex-lax Senna",
    "Exocin", "Exorex lotion", "Extavia", "Exterol", "Ezetimibe", "Ezetimibe/Simvastatin", "Ezetrol",

    "Factor II/Factor VII/Protein S/Factor X/Protein C/Factor IX", "Factor IX high purity", "Factor VIII/von Willebrand factor", "Factor XIII", "Famciclovir", "Famotidine/Calcium carbonate/Magnesium hydroxide",
    "Famvir", "Fareston", "Fasigyn", "Faslodex", "Faverin", "Febuxostat", "Fedril Night Cold and Flu Oral Solution", "Felbinac", "Feldene", "Felendil", "Felodipine", "Felodipine/Ramipril", "Felogen", "Felotens",
    "Femapak", "Femara", "Fematrix", "Femodene", "Femodette", "Femoston", "FemSeven patches", "Femulen", "Fenactol", "Fendrix", "Fenistil", "Fenofibrate", "Fenticonazole nitrate", "Ferinject", "Ferric carboxymaltose",
    "Ferriprox", "Fesoterodine fumarate", "Fexofenadine hydrochloride", "Fibrazate", "Fibrogammin P", "Fibro-Vein", "Filgrastim", "Finacea", "Finasteride", "Fingolimod hydrochloride", "Flagyl", "Flagyl-S",
    "Flavoxate hydrochloride", "Flecainide", "Flexin", "Flixonase", "Flixotide", "Flolan", "Flomaxtra", "Florinef", "Floxapen", "Fluanxol", "Fluarix", "Flucloxacillin sodium", "Fluconazole", "Flucytosine",
    "Fludara", "Fludarabine phosphate", "Fludrocortisone acetate", "Fluimucil N", "Flumazenil", "Fluorescein sodium/Lidocaine hydrochloride", "Fluorescein sodium/Proxymetacaine hydrochloride", "Fluorometholone",
    "Fluorouracil", "Fluorouracil sodium", "Fluoxetine", "Flupentixol", "Flupentixol decanoate", "Fluphenazine decanoate", "Flurazepam", "Flurbiprofen", "Flurbiprofen sodium", "Fluticasone furoate",
    "Fluticasone propionate", "Fluticasone/Salmeterol", "Fluvastatin", "Fluvirin", "Fluvoxamine", "FML", "Folic Acid", "Follitropin Alfa", "Follitropin alfa/Lutropin alfa", "Follitropin Beta", "Fondaparinux",
    "Foradil", "Formaldehyde", "Formoterol fumarate dihydrate", "Forsteo", "Fortipine", "Fortum", "Fosamax", "Fosamprenavir calcium", "Fosavance", "Foscarnet sodium", "Foscavir", "Fosinopril", "Fosphenytoin Sodium",
    "Fosrenol", "Fostair", "Fragmin", "Freederm gel", "Frisium", "Froben", "Frovatriptan succinate monohydrate", "Fru-Co", "Frumil", "Frusene", "Frusol", "Fucibet", "Fucidin cream", "Fucidin H", "Fucidin ointment",
    "Fucidin suspension", "Fucidin tablets", "Fucithalmic", "Fulvestrant", "Fungizone", "Furadantin", "Furosemide", "Furosemide/Spironolactone", "Furosemide/Triamterene", "Fusidic Acid",
    "Fusidic acid/Hydrocortisone acetate", "Fuzeon", "Fybogel", "Fybogel Hi-Fibre", "Fybogel Mebeverine",

    "Gabapentin", "Gadobutrol", "Gadoteridol", "Gadovist", "Gadoxetate disodium", "Galantamine hydrobromide", "Galenphol", "Galenphol Paediatric Linctus", "Galvus", "Gamanil", "Ganciclovir sodium", "Ganfort",
    "Ganirelix", "Gardasil", "Garlic oil/Garlic/Echinacea", "Gastrobid", "Gastrocote liquid", "Gastrocote tablets", "Gaviscon Advance", "Gaviscon Cool tablets", "Gaviscon Double Action",
    "Gaviscon Infant oral powder", "Gaviscon Instants Tropical Fruit Flavour Oral Powder", "Gaviscon liquid sachets", "Gaviscon tablets", "Gefitinib", "GelTears", "Gemcitabine hydrochloride", "Gemeprost",
    "Gemfibrozil", "Gemzar", "Generic Actonorm powder", "Generic Antitis tablets", "Generic Catarrh relief mixture", "Generic Chest mixture", "Generic Cymalon granules", "Generic Deep Heat spray",
    "Generic Dioralyte powder", "Generic Dioralyte Relief", "Generic Dubam cream", "Generic Electrolade powder", "Generic Fiery Jack cream", "Generic Germolene antiseptic ointment",
    "Generic glycerin, honey and lemon linctus", "Generic Karvol Decongestant capsules", "Generic Karvol Decongestant drops", "Generic Ketovite liquid", "Generic Laxido", "Generic Lipobase", "Generic Meted shampoo",
    "Generic Oxymetazoline", "Generic Phytex", "Generic Polytar emollient", "Generic Polytar liquid", "Generic Polytar Plus liquid", "Generic Potter's Strong Bronchial Catarrh pastilles",
    "Generic Potter's sugar free cough pastilles", "Generic Rehydration powder", "Generic Sciargo tablets", "Generic Senokot Comfort tablets", "Generic Senokot Dual Relief tablets", "Generic Sudocrem cream",
    "Generic TCP antiseptic cream", "Generic TCP Antiseptic ointment", "Generic Throaties strong original pastilles", "Generic Unguentum M cream", "Generic Vegetable Cough Remover elixir", "Genotropin",
    "Gentamicin sulphate", "Gentamicin sulphate/Hydrocortisone acetate", "Gentisone", "Germolene Antiseptic cream", "Germolene Antiseptic ointment", "Germoloids cream", "Germoloids Duo Pack", "Germoloids HC spray",
    "Germoloids ointment", "Germoloids suppositories", "Gestone", "Gilenya", "Glatiramer acetate", "Gliadel", "Gliclazide", "Glimepiride", "Glipizide", "Glivec", "GlucaGen", "Glucagon", "Glucobay", "Glucophage",
    "Glucose anhydrous", "Glucose/Treacle Cough mixture", "Glutaraldehyde", "Glutarol", "Glycerin and Blackcurrant cough syrup", "Glycerin, Honey and Lemon linctus", "Glycerin, Honey, Lemon and Ipecacuanha linctus",
    "Glycerol cream", "Glycerol liquid", "Glycerol skin wash", "Glycerol/Sucrose Cough mixture", "Glycerol/Syrup/Citric acid/Honey/Lemon", "Glycerol/White soft paraffin/Liquid paraffin", "Glyceryl Trinitrate",
    "Glycopyrronium bromide", "Goddards Muscle lotion", "Golimumab", "Gonapeptyl", "Gopten", "Goserelin acetate", "Granisetron hydrochloride", "Granocyte-13", "Grass pollen extract", "Grazax", "Griseofulvin",
    "Grisol AF", "Guaiacol/Codeine", "Guaifenesin", "Guaifenesin/Ammonium chloride/Ammonium carbonate", "Guaifenesin/Levomenthol", "Guaifenesin/Pseudoephedrine", "Guaifenesin/Treacle/Glucose", "Guanethidine",
    "Gygel", "Gyno-Daktarin", "Gyno-Pevaryl", "Gynoxin",

    "Haemate P", "Haemophilus influenzae type b polysaccharide tetanus toxoid conjugate/Neisseria meningitidis group C strain C11 capsular polysaccharide tetanus toxoid conjugate", "Haemorrhoid Relief ointment",
    "Haldol", "Haldol decanoate", "Halogenated phenols/Phenol", "Haloperidol", "Haloperidol decanoate", "Happinose", "Havrix", "Haymine Tablets", "HBvaxPRO", "Hedex", "Hedex Extra", "Hedex Ibuprofen",
    "Hedrin Lotion", "Helixate NexGen", "Hemabate", "Heparin sodium", "Hepatitis A virus (GBM strain) inactivated/Salmonella typhi (Ty2 strain) Vi capsular polysaccharide",
    "Hepatitis A virus (HM175 strain) inactivated/Salmonella typhi (Ty2 strain) Vi capsular polysaccharide", "Hepatitis A virus inactivated", "Hepatitis A virus inactivated/Hepatitis B virus surface antigen",
    "Hepatitis B immunoglobulin human", "Hepatitis B virus surface antigen", "Hepatyrix", "Hepsal", "Hepsera", "Herceptin", "Hexetidine", "Hexopal", "Hexylresorcinol", "Hexylresorcinol/Benzalkonium chloride",
    "Hiprex", "Histac", "Histamine dihydrochloride", "Histrelin acetate", "Honey/Glucose/Lemon", "Honey/Menthol", "Horizem", "Hormonin", "Humalog", "Humalog Mix",
    "Human papillomavirus type 16 L1 protein/Human papillomavirus type 18 L1 protein",
    "Human papillomavirus type 6 L1 protein/Human papillomavirus type 11 L1 protein/Human papillomavirus type 16 L1 protein/Human papillomavirus type 18 L1 protein", "Humatrope", "Humira", "Humulin I",
    "Humulin M3", "Humulin S", "Hyaluronidase", "Hycamtin", "Hydralazine", "Hydrea", "Hydrochlorothiazide/Losartan", "Hydrochlorothiazide/Olmesartan", "Hydrochlorothiazide/Quinapril", "Hydrochlorothiazide/Telmisartan",
    "Hydrochlorothiazide/Valsartan", "Hydrocortisone", "Hydrocortisone acetate", "Hydrocortisone acetate/Lidocaine", "Hydrocortisone acetate/Pramocaine hydrochloride", "Hydrocortisone butyrate",
    "Hydrocortisone Sodium Phosphate", "Hydrocortisone Sodium Succinate", "Hydrocortisone/Lactic Acid/Urea", "Hydrocortisone/Lidocaine", "Hydrocortisone/Miconazole nitrate", "Hydrocortisone/Urea", "Hydrocortistab",
    "Hydroflumethiazide/Spironolactone", "Hydrotalcite suspension", "Hydroxocobalamin", "Hydroxycarbamide", "Hydroxychloroquine", "Hydroxyzine hydrochloride", "Hygroton", "Hyoscine", "Hyoscine Butylbromide",
    "Hyoscine Hydrobromide", "Hypnomidate", "Hypnovel", "Hypolar", "Hypovase", "Hypromellose", "Hypromellose/Dextran 70", "Hypurin Bovine Isophane", "Hypurin Bovine Lente", "Hypurin Bovine Neutral",
    "Hypurin Bovine Protamine Zinc", "Hypurin Porcine", "Hypurin Porcine Isophane", "Hypurin Porcine Neutral", "Hytrin",

    "Ibandronic sodium monohydrate", "Ibuprofen", "Ibuprofen/Codeine phosphate", "Ibuprofen/Levomenthol", "Ibuprofen/Phenylephrine", "Ibuprofen/Pseudoephedrine", "Idarubicin hydrochloride", "Iglu gel",
    "Iglu Pastilles", "Ikorel", "Iloprost trometamol", "Ilube", "Imatinib mesilate", "Imigran", "Imigran nasal spray", "Imigran Recovery", "Imipramine hydrochloride", "Imiquimod", "ImmuCyst", "Imodium",
    "Imodium Plus", "Implanon", "Imunovir", "Imuran", "Imuvac", "Incivo", "Increlex", "Indacaterol maleate", "Indapamide", "Indapamide hemihydrate", "Indapamide/Perindopril arginine", "Inderal", "Indivina",
    "Indolar", "Indometacin", "Indoramin hydrochloride", "Inegy", "Infacol", "Infanrix IPV", "Infliximab", "Influenza split virion inactivated vaccine", "Influenza surface antigen inactivated vaccine",
    "Influvac", "Innohep", "Innovace", "Innozide", "Inosine Pranobex", "Inositol Nicotinate", "Inovelon", "Inspra", "Insulatard", "Insulin aspart", "Insulin aspart/Insulin aspart protamine", "Insulin detemir",
    "Insulin Glargine", "Insulin glulisine", "Insulin isophane bovine", "Insulin isophane human", "Insulin isophane human/Insulin soluble human", "Insulin isophane porcine",
    "Insulin isophane porcine/Insulin soluble porcine", "Insulin lispro", "Insulin lispro/Insulin lispro protamine", "Insulin protamine zinc bovine", "Insulin soluble bovine", "Insulin soluble human",
    "Insulin soluble porcine", "Insulin zinc suspension mixed bovine", "Insuman Basal", "Insuman Comb", "Insuman Rapid", "Intal", "Integrilin", "Intelence", "Interferon alfa-2a (rbe)", "Interferon alfa-2b (rbe)",
    "Interferon beta-1a", "Interferon beta-1b", "IntronA", "Invanz", "Invega", "Invirase", "Iopidine", "Ipocol", "Ipratropium", "Ipratropium/Salbutamol", "Irbesartan", "Iressa", "Irinotecan hydrochloride trihydrate",
    "Iron Dextran", "Iron Sucrose", "Isentress", "Ismelin", "Isocarboxazid", "Isoflurane", "Isoket", "Isoniazid", "Isoniazid/Pyrazinamide/Rifampicin", "Isoniazid/Rifampicin", "Isopropyl myristate/Liquid paraffin",
    "Isopto Alkaline", "Isopto Plain", "Isosorbide Dinitrate", "Isosorbide Mononitrate", "Isotretinoin", "Isotrex", "Isotrexin", "Isovorin", "Ispaghula husk granules", "Ispaghula husk/Mebeverine", "Isradipine",
    "Istin", "Itraconazole", "Ivabradine", "Ixiaro",

    "J Collis Browne’s Mixture", "Janumet", "Januvia", "Japanese encephalitis virus (inactivated) vaccine", "Javlor", "Jevtana",

    "Kaletra", "Kaolin and Morphine mixture", "Kaolin Mixture", "Kaolin Mixture for Children", "Kaolin/Calcium carbonate", "Karvol Decongestant capsules", "Karvol Decongestant drops", "Kefadim", "Keflex", "Keftid",
    "Kemadrin", "Kemicetine", "Kenalog", "Kentera", "Kentipine", "Kenzem", "Keppra", "Keral", "Ketalar", "Ketamine hydrochloride", "Ketek", "Ketocid", "Ketoconazole", "Ketoprofen", "Ketorolac trometamol", "Ketotifen",
    "Ketovail", "Ketovite liquid", "Kivexa", "Klaricid", "Kliofem", "Kliovance", "Kolanticon gel", "Kytril",

    "Lacidipine", "Lacosamide", "Lacrilube", "Lactulose", "Lamictal", "Lamisil", "Lamivudine", "Lamivudine/Zidovudine", "Lamotrigine", "Lanacane cream", "Lanoxin", "Lanreotide acetate", "Lansoprazole",
    "Lanthanum carbonate", "Lantus", "Lanvis", "Lapatinib ditosylate monohydrate", "Larapam", "Largactil", "Lariam", "Laryng-O-Jet", "Lasilactone", "Lasix", "Lasoride", "Latanoprost", "Latanoprost/Timolol maleate",
    "Lauromacrogol 400/Heparinoid", "Laxido", "Lecicarbon A Suppository", "Leflunomide", "Lemon/Honey/Levomenthol/Citric acid Over-the-counter medicine", "Lemsip Cold and Flu", "Lemsip Cough Chesty",
    "Lemsip Cough for Mucus Cough Colour & Sugar free Solution", "Lemsip Cough for Mucus Cough Solution", "Lemsip Cough Max for Mucus Cough & Cold", "Lemsip Dry Cough liquid",
    "Lemsip Flu 12 Hour Ibuprofen And Pseudoephedrine", "Lemsip Max All Day Cold and Flu tablets", "Lemsip Max All in One Breathe Easy Over-the-counter medicine", "Lemsip Max All in One Liquid",
    "Lemsip Max All Night Cold and Flu tablets", "Lemsip Max All-In-One", "Lemsip Max Cold and Flu Breathe Easy", "Lemsip Max Cold and Flu Capsules Over-the-counter medicine", "Lemsip Max Cold and Flu Direct",
    "Lemsip Max Cold and Flu Powder", "Lemsip Max Day And Night Cold And Flu Relief capsules", "Lemsip Max Daytime Cold & Flu Relief Over-the-counter medicine", "Lemsip Max Flu",
    "Lemsip Max Powder for Oral Solution Over-the-counter medicine", "Lemsip Max Sinus", "Lemsip Max Sinus capsules", "Lemsip Max Tablets", "Lenalidomide", "Lenograstim (rch)", "Lercanidipine", "Lescol", "Letrozole",
    "Leukeran", "Leuprorelin acetate", "Leustat", "Levemir", "Levetiracetam", "Levitra", "Levobunolol hydrochloride", "Levobupivacaine hydrochloride", "Levocetirizine dihydrochloride", "Levofloxacin hemihydrate",
    "Levomenthol", "Levomenthol/Amylmetacresol/Dichlorobenzyl alcohol", "Levomepromazine maleate", "Levonelle", "Levonorgestrel", "Levothyroxine sodium", "Lexpec Folic Acid", "Librium", "Lidocaine",
    "Lidocaine hydrochloride", "Lidocaine hydrochloride/Adrenaline acid tartrate", "Lidocaine/Aminoacridine", "Lidocaine/Cetalkonium chloride", "Lidocaine/Cetylpyridinium chloride",
    "Lidocaine/Chlorocresol/Cetylpyridinium chloride", "Lidocaine/Methylprednisolone acetate", "Lidocaine/Zinc sulphate/Cetrimide", "Light liquid paraffin", "Li-Liquid", "Linezolid", "Lioresal", "Liothyronine sodium",
    "Lipantil", "Lipitor", "Lipobase", "Lipostat", "Liqufilm Tears", "Liquid Paraffin", "Liquid paraffin/Acetylated wool alcohols Over-the-counter medicine", "Liquid paraffin/White soft paraffin",
    "Liquid paraffin/Wool alcohols/White soft paraffin", "Liquivisc", "Liraglutide", "Lisdexamfetamine dimesylate", "Lisinopril", "Lisinopril/Hydrochlorothiazide", "Liskonum", "Lisopress", "Litak", "Lithium Carbonate",
    "Lithium citrate", "Livial", "Loceryl", "Locoid", "Lodine", "Lodoxamide trometamol", "Loestrin", "Lofepramine", "Logynon", "Lomont", "Lomustine", "Loniten", "Lopace", "Loperamide hydrochloride", "Lopid",
    "Lopinavir/Ritonavir", "Loprazolam", "Lopresor", "Loratadine", "Lorazepam", "Loron 520", "Losartan", "Losec", "Losec IV", "Losec MUPS", "Lotemax", "Loteprednol etabonate", "Lucentis", "Lumigan", "Lustral",
    "Lutropin Alfa", "Luveris", "Lyclear Cream Rinse", "Lyclear Dermal Cream", "Lyflex", "Lymecycline", "Lypsyl Cold Sore gel", "Lyrica", "Lyrinel", "Lysine acetylsalicylate/Metoclopramide hydrochloride", "Lysodren", "Lysovir",

    "Maalox", "Maalox Plus", "MabThera", "Mackenzies Smelling Salts", "Macrobid", "Macrodantin", "Macrogol 4000", "Macrogol compound powder NPF", "Macugen", "Madopar", "Magnapen vial",
    "Magnesium hydroxide oral suspension", "Magnesium hydroxide/Simeticone/Aluminium hydroxide gel dried", "Magnesium trisilicate/Sodium bicarbonate/Alginic acid/Aluminium hydroxide", "Magnevist", "Malarone",
    "Malathion", "Manerix", "Maraviroc", "Marcain Heavy", "Marcain Polyamp Steripack", "Marevan", "Marvelon", "Mastaflu", "Maxalt", "Maxidex", "Maxitrol eye drops", "Maxitrol eye ointment", "Maxolon", "Maxtrex",
    "Measles virus live attenuated/Mumps virus live attenuated/Rubella virus live attenuated", "Mebendazole", "Mebeverine Hydrochloride", "Mecasermin", "Meclozine", "Medicated talc", "Medijel gel", "Medrone",
    "Medroxyprogesterone acetate", "Mefenamic", "Mefloquine hydrochloride", "Megace", "Megestrol acetate", "Meggezones", "Meglumine gadobenate", "Meglumine gadopentetate", "Melatonin", "Melphalan",
    "Melphalan hydrochloride", "Memantine hydrochloride", "Menadiol sodium phosphate", "Meningitec", "Menitorix", "Menjugate", "Menopur", "Menotrophin", "Menthol pastilles", "Menthol/Anise oil",
    "Menthol/Camphor/Pine Needle oil", "Menthol/Eucalyptus", "Menthol/Pine Sylvestris oil/Abietis oil", "Mepradec", "Mepyramine", "Merbentyl", "Mercaptopurine", "Mercilon", "Merional", "Meronem",
    "Meropenem trihydrate", "Mesalazine", "Mesren", "Mesterolone", "Mestinon", "Mestranol/Norethisterone", "Metalyse", "Metanium Nappy Rash Ointment", "Meted", "Meted Shampoo", "Metformin",
    "Metformin hydrochloride/Sitagliptin phosphate", "Metformin hydrochloride/Vildagliptin", "Metformin/Pioglitazone", "Methenamine hippurate", "Methotrexate", "Methotrexate sodium",
    "Methoxy polyethylene glycol-epoetin beta", "Methyl aminolevulinate hydrochloride", "Methyl salicylate", "Methyl salicylate/Menthol", "Methyl salicylate/Menthol/Camphor",
    "Methyl salicylate/Menthol/Capsicum/Camphor", "Methylcellulose", "Methylnaltrexone bromide", "Methylphenidate hydrochloride", "Methylprednisolone", "Methylprednisolone acetate",
    "Methylprednisolone sodium succinate", "Methysergide maleate", "Metoclopramide", "Metoclopramide hydrochloride/Paracetamol", "Metopirone", "Metoprolol", "Metrogel", "Metrolyl", "Metronidazole",
    "Metronidazole benzoate", "Metrosa", "Metrotop", "Metvix", "Metyrapone", "Miacalcic", "Micafungin sodium", "Micardis", "MicardisPlus", "Miconazole", "Miconazole nitrate", "Microgynon 30", "Micronor", "Micropirin",
    "Midazolam hydrochloride", "Mifegyne", "Mifepristone", "Migard", "Migril", "Mildison Lipocream", "Milrinone", "Mimpara", "Minijet adrenaline", "Minijet amiodarone", "Minijet Atropine", "Minijet Furosemide",
    "Minijet Lidocaine", "Minijet Naloxone", "Minijet Sodium Bicarbonate", "Minims Artificial Tears", "Minims atropine", "Minims Chloramphenicol", "Minims cyclopentolate hydrochloride", "Minims Dexamethasone",
    "Minims Lidocaine and Fluorescein", "Minims pilocarpine nitrate", "Minims prednisolone", "Minims proxymetacaine and fluorescein", "Minims Saline Eye Drops", "Minims tetracaine hydrochloride", "Minims Tropicamide",
    "Mini-Plasco Lidocaine", "Minocin", "Minocycline hydrochloride", "Minodiab", "Minoxidil", "Mintec", "Miochol-E", "Mirapexin", "Mircera", "Mirena", "Mirtazapine", "Misoprostol", "Misoprostol/Naproxen", "Mitomycin",
    "Mitomycin-C Kyowa", "Mitotane", "Mitoxantrone hydrochloride", "Mivacron", "Mivacurium chloride", "Mixtard", "Mizolastine", "Mizollen", "MMRVAXPRO", "Mobiflex", "Moclobemide", "Modafinil", "Modalim", "Modecate",
    "Moduret", "Moduretic", "Moexipril", "Mogadon", "Molaxole", "Molipaxin", "Mometasone", "Mometasone furoate", "Monomil", "Monosorb", "Montelukast sodium", "Morphine", "Motens", "Motifene", "Motilium",
    "Motilium tablet", "Movelat", "Movicol", "Moxifloxacin hydrochloride", "Moxisylyte hydrochloride", "Moxonidine", "Mucodyne", "Mucogel", "Multaq", "Multi-Action Actifed tablets", "MultiHance", "Multiparin",
    "Mupirocin calcium", "Muse", "Mycamine", "Mycil Athletes Foot spray", "Mycil ointment", "Mycil powder", "Mycobutin", "Mycophenolate mofetil", "Mycophenolate mofetil hydrochloride", "Mycophenolate sodium",
    "Mycota", "Myfortic", "Myleran", "Myocet", "Myocrisin", "Myotonine", "Mysoline",

    "Nabilone", "Nabumetone", "Nadolol", "Nafarelin acetate", "Naftidrofuryl", "Nalcrom", "Naloxone hydrochloride", "Nandrolone decanoate", "Naphazoline", "Napratec", "Naprosyn", "Naproxen",
    "Naproxen/Esomeprazole magnesium trihydrate", "Naramig", "Naratriptan hydrochloride", "Naropin", "Nasacort", "Naseptin", "Nasofan", "Nasonex", "Natalizumab", "Natecal D3", "Nateglinide", "Natrasleep", "Natrilix",
    "Natrilix SR", "Navelbine", "Nebido", "Nebilet", "Nebivolol", "Nedocromil",
    "Neisseria meningitidis group A capsular polysaccharide/Neisseria meningitidis group C capsular polysaccharide/Neisseria meningitidis group W135 capsular polysaccharide/Neisseria meningitidis group Y capsular polysaccharide",
    "Neisseria meningitidis group C capsular polysaccharide protein conjugate", "Nelarabine", "Neoclarityn", "Neo-Cytamen", "Neofel", "NeoMercazole", "Neomycin sulphate", "Neo-Naclex", "Neoral", "NeoRecormon",
    "Neostigmine metilsulfate", "Neostigmine metilsulfate/Glycopyrronium bromide", "Neotigason", "Neulactil", "Neulasta", "Neupogen", "Neupro", "Neurobloc", "Neurontin", "Neutrogena Norwegian Formula cream",
    "Neutrogena T-Gel shampoo", "Nevirapine", "Nevirapine hemihydrate", "Nexavar", "Nexium", "Nexium IV", "Nicam gel", "Nicardipine", "Nicorandil", "Nicotinamide", "Nifedipine", "Nifopress", "Night Nurse",
    "Nilotinib hydrochloride monohydrate", "Nimbex", "Nimodipine", "Nimotop", "Nipent", "Nirolex Chesty Cough linctus", "Nirolex Dry Cough linctus", "Nirolex Dry Cough Relief lozenges",
    "Nirolex Dry Coughs with Decongestant", "Nitrazepam", "Nitrofurantoin", "Nizatidine", "Nizoral", "Nonacog Alfa", "Non-Drowsy Sudafed Childrens syrup", "Nonoxinol-9", "Nootropil", "Noradrenaline acid tartrate",
    "Norcuron", "Norditropin NordiFlex", "Norditropin SimpleXx", "Norethisterone", "Norethisterone enantate", "Norgalax", "Norgeston", "Noriday", "Norimin", "Norimode", "Norinyl-1", "Noristerat", "Normacol",
    "Normacol Plus", "Normal immunoglobulin human", "Nortriptyline", "Norvir", "Norzol", "Novofem", "NovoMix 30", "NovoRapid", "NovoSeven", "Noxafil", "Nozinan tablets", "Nupercainal", "Nurofen",
    "Nurofen Back Pain 300mg Sustained Release Capsules", "Nurofen Cold & Flu Relief Tablets", "Nurofen Cold And Flu", "Nurofen Day & Night Cold & Flu Tablets", "Nurofen Express 256mg Caplets",
    "Nurofen Express 256mg Tablets", "Nurofen Express 342mg Caplets", "Nurofen Express 684mg Caplets", "Nurofen Express Liquid Capsules", "Nurofen Express Period Pain 200mg capsules",
    "Nurofen Express Soluble 400mg Oral Powder", "Nurofen Maximum Strength Migraine Pain 684mg Caplets", "Nurofen Meltlets", "Nurofen Migraine Pain/Tension Headache", "Nurofen Plus", "Nuromol", "Nu-Seals", "Nutrizym",
    "NutropinAq", "NuvaRing", "Nyogel", "Nystan", "Nystatin", "Nytol",

    "Occlusal", "Octim", "Octocog Alfa", "Octreotide acetate", "Ocufen", "Ofatumumab", "Ofloxacin", "Ofloxacin hydrochloride", "Oilatum cream", "Oilatum emollient", "Oilatum gel", "Oilatum Junior bath additive",
    "Oilatum Junior cream", "Oilatum Shower Gel fragrance-free", "Olanzapine", "Olanzapine pamoate monohydrate", "Olbetam", "Olmesartan", "Olmetec", "Olmetec Plus", "Olopatadine hydrochloride", "Olsalazine sodium",
    "Omalizumab", "Omeprazole", "Omeprazole magnesium", "Omeprazole sodium", "OncoTICE", "Ondansetron", "Ondansetron hydrochloride", "One-Alpha", "Onglyza", "Onkotrone", "Opatanol", "Opilon", "Opticrom", "Optilast",
    "Optimax", "Optivate", "Optrex Sore Eye Drops", "Orajel", "Orajel Extra Strength", "Oraldene", "Orap", "Orencia", "Orgalutran", "Orgaran", "Original Andrews Salts", "Orlept", "Orlistat",
    "Orphenadrine hydrochloride", "Ortho-Gynest", "Orudis", "Oruvail", "Otex", "Otomize", "Otrivine Adult Measured Dose Sinusitis spray", "Otrivine Adult Menthol nasal spray", "Otrivine Adult nasal drops",
    "Otrivine Adult nasal spray", "Otrivine Allergy Relief Nasal Spray", "Otrivine Antistin Eye Drops", "Otrivine Child nasal drops", "Otrivine Mu-Cron", "Ovestin", "Ovitrelle", "Ovranette", "Ovysmen", "Oxactin",
    "Oxaliplatin", "Oxcarbazepine", "Oxerutins", "Oxis", "Oxprenolol", "Oxybuprocaine hydrochloride", "Oxybutynin", "Oxybutynin hydrochloride", "Oxymetazoline", "Oxytetracycline dihydrate", "Oxytocin",

    "Pabal", "Paclitaxel", "Paclitaxel albumin", "Pain Relief balm", "Paliperidone", "Paliperidone palmitate", "Paludrine", "Panadol", "Panadol ActiFast", "Panadol ActiFast Soluble Tablets",
    "Panadol Extra Advance Tablets", "Panadol Extra Soluble tablets", "Panadol Night", "Panadol Period Pain", "Panadol Ultra", "Pancrease", "Pancrex", "Pancuronium bromide", "Panitumumab", "PanOxyl 10 Acnegel",
    "PanOxyl Aquagel", "PanOxyl cream", "PanOxyl wash", "Pantoprazole", "Paracetamol", "Paracetamol/Caffeine", "Paracetamol/Codeine /Caffeine", "Paracetamol/Dihydrocodeine", "Paracetamol/Diphenhydramine tablets",
    "Paracetamol/Phenylephrine sachets", "Paracetamol/Phenylephrine/Caffeine", "Paracetamol/Pseudoephedrine", "Paracetamol/Tramadol hydrochloride", "Paramax", "Paramol tablets", "Pardelprin", "Parecoxib sodium",
    "Paricalcitol", "Pariet", "Parlodel", "Parmid", "Paroven", "Paroxetine", "Passion flower/Valerian/Hops", "Passion flower/Valerian/Hops/Scullcap/Jamaica dogwood", "Pavacol-D", "Paxoran",
    "PediacelProtein Conjugate)", "Pegaptanib sodium", "Pegasys", "Pegfilgrastim", "Peginterferon alfa-2a", "Peginterferon alfa-2b (rbe)", "PegLax", "Pegvisomant", "Pemetrexed disodium", "Penbritin", "Penciclovir",
    "Penicillamine", "Pennsaid", "Pentasa", "Pentostatin", "Pentoxifylline", "Pentrax shampoo", "PepcidTwo", "Peppermint oil capsules", "Peppermint oil/Capsicum/Elder flower",
    "Peppermint oil/Cinnamon/Clove oil/Slippery Elm bark", "Peppermint oil/Menthol/Benzoin compound/Ipecacuanha", "Peppermint oil/Menthol/Myrrh", "Pepto-Bismol", "Perdix", "Perfalgan", "Pergoveris", "Periactin",
    "Pericyazine", "Perinal spray", "Perindopril", "Perindopril arginine", "Permethrin", "Persantin", "Pevaryl", "Pharmorubicin", "Phenelzine sulphate", "Phenergan", "Phenol/Aromatic ammonia/Strong ammonia",
    "Phenol/Chlorhexidine gluconate", "Phenylephrine hydrochloride", "Phenylephrine hydrochloride/Caffeine/Paracetamol", "Phenylephrine/Caffeine/Paracetamol dual relief",
    "Phenylephrine/Caffeine/Paracetamol max strength capsules", "Phenylephrine/Guaifenesin/Paracetamol", "Phenylephrine/Guaifenesin/Paracetamol/Cetylpyridinium chloride", "Phenylethyl alcohol/Undecenoic acid/Cetrimide",
    "Phenytoin", "Phenytoin Sodium", "Phillips Milk Of Magnesia", "Pholcodine", "Pholcodine Childrens Oral solution", "Pholcodine linctus", "Phosex", "Phyllocontin", "Physiotens", "Pilocarpine hydrochloride",
    "Pilocarpine nitrate", "Pimecrolimus", "Pimozide", "Pindolol", "Pinefeld", "Pioglitazone", "Piperacillin sodium/Tazobactam sodium", "Piportil", "Pipotiazine palmitate", "Piracetam", "Piriteze Allergy syrup",
    "Piriteze Allergy tablets", "Piriton", "Piroxicam", "Pitressin", "Pivmecillinam hydrochloride", "Pizotifen hydrogen malate", "Plaquenil", "Plavix", "Plendil", "Pletal", "Pneumovax II", "Podophyllotoxin",
    "Pollenshield", "Polytar emollient", "Polytar liquid", "Polytar Plus liquid", "Polyvinyl alcohol", "Ponstan", "Pork Actrapid", "Pork Mixtard", "Posaconazole", "Potassium citrate", "Potassium citrate/Citric acid",
    "Potassium clavulanate/Ticarcillin sodium", "Povidone-Iodine Spray", "Powergel", "Pradaxa", "Pramipexole dihydrochloride monohydrate", "Prandin", "Prasugrel hydrochloride", "Pravastatin sodium", "Praxilene",
    "Prazosin", "Pred Forte", "Prednisolone", "Prednisolone acetate", "Prednisolone Sodium Phosphate", "Predsol", "Pregabalin", "Pregnyl", "Premarin", "Premique", "Prempak-C", "Prescal", "Preservex", "Prestim",
    "Prevenar", "Prezista", "Priadel liquid", "Priadel tablets", "Prilocaine hydrochloride", "Prilocaine/Lidocaine", "Primacor", "Primaxin", "Primidone", "Primolut N", "Primovist", "Priorix", "Procarbazine hydrochloride",
    "Prochlorperazine maleate", "Prochlorperazine mesilate", "Procoralan", "Proctofoam", "Proctosedyl", "Procyclidine hydrochloride", "Pro-Epanutin", "Progesterone", "Prograf", "Prograf Infusion",
    "Proguanil hydrochloride", "Progynova patches", "Progynova tablets", "ProHance", "Proleukin", "Prolia", "Promethazine", "Promethazine hydrochloride/Dextromethorphan hydrobromide/Paracetamol",
    "Promethazine/Dextromethorphan/Paracetamol", "Promixin", "Propaderm", "Propafenone", "Propantheline bromide", "Propecia", "Propess", "Propiverine hydrochloride", "Propofol", "Propranolol", "Proscar", "Prostap",
    "Prostin E2", "Prosulf", "Protamine", "Protelos", "Protium", "Protopic", "Provera", "Provigil", "Pro-Viron", "Proxymetacaine hydrochloride", "Prozac", "Pseudoephedrine",
    "Pseudoephedrine hydrochloride/Diphenhydramine hydrochloride/Paracetamol", "Pseudoephedrine/Acrivastine", "Pseudoephedrine/Dextromethorphan", "Pseudoephedrine/Paracetamol/Diphenhydramine",
    "Pseudoephedrine/Pholcodine/Paracetamol", "Pseudoephedrine/Triprolidine", "Pseudoephedrine/Triprolidine/Dextromethorphan", "Pseudoephedrine/Triprolidine/Guaifenesin", "Psoriderm bath additive", "Psoriderm cream",
    "Psoriderm scalp lotion", "Pulmicort", "Pulmo Bailly", "Pulmozyme", "Puregon", "Puri-Nethol", "Pyralvex", "Pyridostigmine bromide", "Pyrimethamine",

    "Questran", "Quetiapine fumarate", "Quinapril", "Quinil", "Quinoderm",

    "Rabeprazole", "Rabies immunoglobulin human", "Rabies Vaccine", "Rabipur", "Radian B Muscle Lotion", "Radian B Muscle Rub", "Radian B Pain Relief Spray", "Raloxifene hydrochloride", "Raltegravir", "Raltitrexed",
    "Ramipril", "Ranexa", "Ranibizumab", "Ranitic", "Ranitidine hydrochloride", "Ranitil", "Ranolazine", "Rapamune", "Rapifen", "Rapilysin", "Rapitil", "Rasagiline mesilate", "Rasilez", "Rebetol", "Rebif", "Reboxetine",
    "Rectogesic", "Refolinon", "Regurin", "Relenza", "Relestat", "Relifex", "Relistor", "Relpax", "Remedeine", "Remegel", "Remicade", "Remifentanyl hydrochloride", "Reminyl", "Renagel", "Renvela", "ReoPro",
    "Repaglinide", "Repevax", "Replenine-VF", "ReQuip", "Resolor", "Respontin", "Restandol", "Retalzem", "Retapamulin", "Reteplase", "Retigabine", "Retin-A", "Retrovir", "Revatio", "Revaxis", "Revlimid", "Reyataz",
    "Rhinocort", "Rhinolast", "Rhophylac", "Rhumalgan", "Riamet", "Rifabutin", "Rifadin", "Rifampicin", "Rifater", "Rifinah", "Rilutek", "Riluzole", "Rimactane", "Rimexolone", "Rinatec", "Rinstead sugar free pastilles",
    "Risedronate sodium", "Risedronate sodium/Colecalciferol/Calcium carbonate", "Risperdal", "Risperidone", "Ritalin", "Ritonavir", "Rituximab", "Rivaroxaban", "Rivastigmine", "Rivastigmine hydrogen tartrate",
    "Rizatriptan benzoate", "Roaccutane", "RoActemra", "Robinul", "Robinul-Neostigmine", "Robitussin Chesty Cough", "Robitussin Chesty Cough With Congestion", "Robitussin Dry Cough Medicine",
    "Robitussin Mucus Cough and Congestion Relief", "Rocaltrol", "Rocephin", "Rocuronium bromide", "Roferon-A", "Roflumilast", "Ropinirole hydrochloride", "Ropivacaine hydrochloride", "Rosiced", "Rosuvastatin",
    "Rotarix", "Rotavirus vaccine", "Rotigotine", "Rozex", "Rufinamide", "Rupafin", "Rupatadine fumarate", "Rynacrom", "Rythmodan", "Rythmodan capsules",

    "Sabril", "Saflutan", "Saizen", "Salactol paint", "Salagen", "Salatac gel", "Salazopyrin", "Salbutamol", "Salicylic acid", "Salicylic acid ointment", "Salicylic acid paint", "Salicylic acid/Camphor",
    "Salicylic acid/Coal tar/Sulphur", "Salicylic acid/Lactic acid", "Salicylic acid/Menthol/Ammonium salicylate/Camphor", "Salicylic acid/Mucopolysaccharide polysulphate", "Salicylic acid/Rhubarb extract",
    "Salmeterol", "Salofalk", "Sandimmun", "Sandocal", "Sandoglobulin NF", "Sandostatin", "Sandrena", "Sanomigran", "Saquinavir mesilate", "Savlon Antiseptic cream", "Savlon Antiseptic liquid", "Savlon dry spray",
    "Savlon First Aid Wash", "Scheriproct", "Scholl Athletes Foot powder", "Scholl Corn Removal Plasters (washproof)", "Scholl Seal and Heal Verruca Removal gel", "Scholl Verruca Removal Medicated Plasters",
    "Scopoderm TTS", "Sea-Legs tablets", "Sebivo", "Sebomin", "Sebren", "Sectral", "Securon", "Selectajet Dopamine", "Selegiline hydrochloride", "Selenium sulphide", "Selexid", "Senna fruit/Ispaghula",
    "Senna syrup", "Senna Tablets", "Senna/Buckthorn bark/Psyllium seeds", "Senokot Comfort tablets", "Senokot Dual Relief tablets", "Senokot Max Strength", "Senokot syrup", "Senokot tablets", "Septrin", "Seractil",
    "Serc", "Serenace", "Seretide", "Serevent", "Seroquel", "Seroxat", "Sertraline", "Setlers Antacid Chewable Tablets", "Sevelamer carbonate", "Sevelamer hydrochloride", "Sevoflurane", "Sildenafil citrate",
    "Silkis", "Silver nitrate", "Simeticone", "Simeticone drops", "Simeticone/Loperamide hydrochloride", "Simple Linctus", "Simple Linctus Paediatric", "Simple Linctus Paediatric Sugar Free",
    "Simple Linctus Sugar Free", "Simponi", "Simulect", "Simvador", "Simvastatin", "Sinemet", "Singulair", "Sinthrome", "Sinutab Non-Drowsy", "Sirolimus", "Skinoren", "Sleepeaze tablets", "Slozem", "SNO Tears",
    "Snufflebabe Vapour rub", "Sodiofolin", "Sodium alginate/Calcium carbonate/Sodium bicarbonate", "Sodium alginate/Magnesium alginate", "Sodium alginate/Potassium bicarbonate", "Sodium Aurothiomalate",
    "Sodium Bicarbonate", "Sodium bicarbonate/Citric acid/Magnesium sulphate", "Sodium bicarbonate/Dill seed oil", "Sodium citrate", "Sodium citrate compound", "Sodium Clodronate", "Sodium Cromoglicate",
    "Sodium fluoride/Triclosan", "Sodium Fusidate", "Sodium lauryl ether sulpho-succinate/Sodium lauryl ether sulphate", "Sodium oxybate", "Sodium picosulfate", "Sodium Tetradecyl Sulfate", "Sodium Valproate",
    "Sofradex Ear/Eye Drops", "Solaraze", "Soleve Sunburn Relief", "Solian", "Solifenacin succinate", "Solpadeine headache soluble tablets", "Solpadeine Max", "Solpadeine Max Soluble Tablets",
    "Solpadeine Migraine ibuprofen and codeine tablets", "Solpadeine Plus Capsules", "Solpadeine Plus Soluble Tablets", "Solpadeine Plus Tablets", "Solu-Cortef", "Solu-Medrone", "Somatropin (epr)",
    "Somatropin (rbe)", "Somatropin (rmc)", "Somatuline", "Somavert", "Sominex Herbal tablets", "Somnite", "Sonata", "SonoVue", "Sorafenib tosylate", "Sotacor", "Sotalol", "Soya oil/Lauromacrogols",
    "Spasmonal", "Spasmonal Forte", "Spiriva", "Spironolactone", "Sporanox", "Sprycel", "Squill/Capsicum", "Squill/Ipecacuanha/Liquorice", "Stalevo", "Stannous fluoride", "Starlix", "Stavudine", "Stelara",
    "Stelazine", "Stemetil", "Stemetil tablet", "Sterculia", "Sterculia/Frangula", "Stesolid", "Stiemycin", "Stilnoct", "Strattera", "Strepsils", "Strepsils Children 6+ Lozenges", "Strepsils Cool",
    "Strepsils Extra lozenges", "Strepsils Honey and Lemon", "Strepsils Orange with Vitamin C", "Strepsils Sore Throat and Blocked Nose lozenges", "Strepsils Strawberry Sugar Free Lozenges", "Strepsils Warm Lozenges",
    "Streptase", "Streptococcus pneumoniae vaccine (capsular polysaccharide protein conjugate)", "Streptococcus pneumoniae vaccine (mixed serotype capsular polysaccharide)", "Streptokinase",
    "Stressless Herbal tablets", "Stronazon", "Strontium ranelate", "Stugeron 15", "Sucralfate", "Sudafed Blocked Nose And Headache Capsules", "Sudafed Blocked Nose And Sinus Capsules", "Sudafed Blocked Nose capsules",
    "Sudafed Blocked Nose spray", "Sudafed Congestion & Headache Relief Day and Night Capsules", "Sudafed Congestion & Headache Relief Max Strength", "Sudafed Day And Night Capsules", "Sudafed Decongestant liquid",
    "Sudafed Decongestant tablets", "Sudafed Dry Coughs with Decongestant", "Sudafed Mucus Relief Day & Night Capsules", "Sudafed Mucus Relief Nasal Spray", "Sudafed Mucus Relief Triple Action Cold & Flu Tablets",
    "Sudafed Non-Drowsy Expectorant", "Sudafed Sinus Max Strength Capsules", "Sudafed Sinus Pressure And Pain Tablets", "Sudocrem", "Sugammadex sodium", "Sulfadiazine", "Sulfasalazine", "Sulphur hexafluoride",
    "Sulphur/salicylic acid", "Sulpiride", "Sulpor", "Sumatriptan", "Sumatriptan succinate", "Sunitinib malate", "Supralip", "Suprax", "Suprecur", "Suprefact", "Sure-Amp Lidocaine", "Surgam", "Surmontil",
    "Sustanon 250", "Sustiva", "Sutent", "Suxamethonium chloride", "Symbicort", "Symmetrel", "Synarel", "Syner-Kinase", "Synflorix", "Synphase", "Syntocinon", "Syntometrine", "Syprol",

    "Tabphyn", "Tacrolimus", "Tacrolimus monohydrate", "Tadalafil", "Tafluprost", "Tagamet", "Tambocor", "Tamiflu", "Tamoxifen citrate", "Tamsulosin hydrochloride", "Tamsulosin hydrochloride/Dutasteride",
    "Tarceva", "Targocid", "Targretin", "Tarivid", "Tarivid injection", "Tarka", "Tasigna", "Tavanic", "Tavegil", "Taxol", "Taxotere", "Tazarotene", "Tazocin", "TCP Antiseptic cream", "TCP Antiseptic liquid",
    "TCP Antiseptic ointment", "TCP sore throat lozenges", "Tears Naturale", "Tegretol", "Teicoplanin", "Telbivudine", "Telfast", "Telithromycin", "Telmisartan", "Telzir", "Temazepam", "Temodal", "Temozolomide",
    "Temsirolimus", "Tenecteplase", "Tenif", "Tenofovir disoproxil fumarate", "Tenofovir disoproxil fumarate/Efavirenz/Emtricitabine", "Tenoret", "Tenoretic", "Tenormin", "Tenoxicam", "Tensipine", "Terazosin",
    "Terbinafine hydrochloride", "Terbutaline", "Teriparatide", "Testim", "Testogel", "Testosterone", "Testosterone decanoate/Testosterone isocaproate/Testosterone phenylpropionate/Testosterone propionate",
    "Testosterone enantate", "Testosterone undecanoate", "Tetanus immunoglobulin human",
    "Tetanus toxoid/Pertussis antigens/Human poliovirus type 1 inactivated/Human poliovirus type 2 inactivated/Human poliovirus type 3 inactivated/Diphtheria toxoid", "Tetracaine hydrochloride",
    "Tetracycline hydrochloride", "Tetralysal", "Teveten", "Theophylline", "Thiopental sodium", "Throaties strong original pastilles", "Thwart", "Thymoglobuline", "Thyrogen", "Thyrotropin alfa",
    "Tiaprofenic Acid", "Tibolone", "Ticagrelor", "Tigecycline", "Tilade", "Tildiem", "Tiloket", "Tiloryth", "Timentin", "Timodine", "Timolol", "Timolol maleate/Travoprost", "Timoptol", "Tinidazole", "Tinzaparin",
    "Tioconazole", "Tioguanine", "Tiotropium", "Tipranavir", "Tirofiban", "Tixylix baby syrup", "Tixylix Blackcurrant Syrup", "Tixylix Chesty Cough", "Tixylix Dry Cough", "Tixylix Honey, Lemon And Glycerol syrup",
    "Tixylix Toddler syrup", "Tizanidine", "TOBI", "Tobradex", "Tobramycin", "Tocilizumab", "Toctino", "Tolcapone", "Tolfenamic Acid", "Tolnaftate", "Tolnaftate/Benzalkonium chloride", "Tolnaftate/Chlorhexidine",
    "Tolterodine tartrate", "Tomudex", "Topamax", "Topiramate", "Topotecan hydrochloride", "Torasemide", "Torem", "Toremifene citrate", "Torisel", "Tostran", "Toviaz", "Tracleer", "Tracrium", "Tramacet",
    "Tramadol hydrochloride", "Trandolapril", "Trandolapril/Verapamil", "Tranexamic Acid", "Transiderm-Nitro", "Trasicor", "Trastuzumab", "Travatan", "Travoprost", "Traxam", "Trazodone", "Trental", "Treosulfan",
    "Tretinoin", "Triadene", "Triamcinolone", "Triamterene/Hydrochlorothiazide", "Triapin", "Tridestra", "Trifluoperazine hydrochloride", "Trihexyphenidyl hydrochloride", "Trileptal", "Trimethoprim",
    "Trimipramine", "Trimovate", "Trinordiol", "Trinovum", "Tripotassium dicitratobismuthate", "Triptorelin acetate", "Trisenox", "Trisequens", "Tritace", "Trizivir", "Trobalt", "Tropicamide", "Trospium chloride",
    "Trosyl", "Trusopt", "Truvada", "Tryptophan", "Tums Antacid tablets", "Turpentine oil/Acetic acid", "Turpentine/Dilute ammonia/Acetic acid", "Twinrix", "Tygacil", "Tylex", "Typherix", "Typhim Vi",
    "Typhoid vaccine (live attenuated)", "Typhoid vaccine (polysaccharide antigen)", "Tyrozets", "Tysabri", "Tyverb",

    "Ulipristal acetate", "Ultiva", "Ultra Chloraseptic Anaesthetic throat spray", "Ultramol soluble tablets", "Unguentum M", "Uniroid HC", "Univer", "Urdox", "Urea", "Urea hydrogen peroxide",
    "Urea/Lauromacrogols", "Urispas", "Urokinase", "Ursodeoxycholic Acid", "Ursofalk", "Ursogal", "Ustekinumab", "Utovlan",

    "Vagifem", "Valaciclovir hydrochloride", "Valcyte", "Valdoxan", "Valerian/Hops", "Valganciclovir hydrochloride", "Vallergan", "Valoid", "Valproate semisodium", "Valsartan", "Valtrex", "Vancomycin hydrochloride",
    "Vaniqa", "Vantas", "VAQTA", "Vardenafil hydrochloride trihydrate", "Vascalpha", "Vectavir", "Vectibix", "Vecuronium bromide", "Veganin", "Velcade", "Velosulin", "Vemurafenib", "Venlafaxine", "Venofer",
    "Venos Cough mixture", "Venos Expectorant", "Venos Honey and Lemon", "Ventavis", "Ventolin", "Vepesid", "Verapamil", "Vera-Til", "Vermox", "Versatis", "Vertab", "Verteporfin", "Vervain/Valerian/Scullcap/Hops",
    "Vervain/Valerian/Scullcap/Hops/Lupulus", "Vesanoid", "Vesicare", "Vexol", "VFEND", "Viagra", "ViATIM", "Viazem", "Vibramycin-D", "Vibrio cholerae", "Vicks inhaler", "Vicks Sinex Decongestant nasal spray",
    "Vicks Sinex Micromist", "Vicks Sinex Soother", "Vicks Vaporub", "Vicks Vaposyrup for Chesty Coughs", "Victoza", "Victrelis", "Videx", "Vigabatrin", "Vigam", "Vildagliptin", "Vimovo", "Vimpat", "Vinblastine",
    "Vinblastine sulphate", "Vincristine sulphate", "Vinflunine ditartrate", "Vinorelbine tartrate", "Viraferon", "ViraferonPeg", "Viramune", "Viramune suspension", "Viread", "Viridal", "Viscotears", "Viskaldix",
    "Visken", "Visudyne", "Vivotif", "Volibris", "Voltarol", "Voltarol Dispersible", "Voltarol Emulgel", "Voltarol Gel Patch", "Voltarol Rapid", "Voriconazole", "Votrient",

    "Warfarin", "Warticon", "Wasp-Eze spray", "Waxsol", "White soft paraffin/Liquid paraffin", "Wind-eze Gel caps", "Wind-eze tablets", "WindSetlers", "Witch Doctor gel", "Witch Hazel gel", "Woodwards Gripe Water",

    "Xalacom", "Xalatan", "Xamiol", "Xanax", "Xarelto", "Xatral", "Xeloda", "Xenical", "Xeplion", "Xipamide", "Xismox", "Xolair", "Xylocaine with Adrenaline", "Xylometazoline", "Xyloproct", "Xyrem", "Xyzal",

    "Yasmin", "Yeast plasmolysate", "Yentreve",

    "Zacin", "Zaditen", "Zafirlukast", "Zaleplon", "Zamadol", "Zanaflex", "Zanamivir", "Zanidip", "Zantac", "Zaponex", "Zarontin", "Zavedos", "Zebinix", "Zeffix", "Zelboraf", "Zemplar", "Zemtard", "Zerit",
    "Zestoretic", "Zestril", "Ziagen", "Zibor", "Zidoval", "Zidovudine", "Zimovane", "Zinacef", "Zinc oxide/Bismuth subgallate/Peru Balsam/Bismuth oxide", "Zinc oxide/Lidocaine",
    "Zinc oxide/Lidocaine/Benzoic acid/Cinnamic acid/Bismuth oxide", "Zinc oxide/Peru Balsam/Bismuth oxide", "Zinc undecenoate/Undecenoic acid", "Zineryt", "Zinnat", "Zirtek Allergy liquid",
    "Zirtek Allergy tablets", "Zispin SolTab", "Zithromax", "Zocor", "Zofran", "Zofran Melt", "Zofran suppository", "Zoladex", "Zoledronic acid monohydrate", "Zolmitriptan", "Zolpidem", "Zolvera",
    "Zomacton", "Zomig", "Zonegran", "Zonisamide", "Zopiclone", "Zorac", "Zoton", "Zovirax", "Zovirax I.V.", "Zuclopenthixol acetate", "Zuclopenthixol decanoate", "Zuclopenthixol dihydrochloride", "Zumenon",
    "Zyloric", "Zyomet", "ZypAdhera", "Zyprexa", "Zyvox"
  ];
